# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nxp-mcuxpresso
      url-base: https://github.com/nxp-mcuxpresso

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.4.0
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nxp   # required by the custom_plank board (Nordic based)
          - libmetal  # required by the nucleo_f302r8 board (STM32 based)
          - open-amp
          - hal_nordic
          - hal_stm32
    - name: rpmsg-lite
      remote: nxp-mcuxpresso
      revision: master
      path: rpmsg-lite
    - name: mcux-sdk-examples
      remote: nxp-mcuxpresso
      revision: main
      path: mcux-sdk-examples

